# Generated by Django 4.1.5 on 2023-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('num1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('num2', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
