# Generated by Django 4.1.5 on 2023-01-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0002_calc_created_calc_total_calc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
