# Generated by Django 4.1.5 on 2023-01-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_app', '0003_calc_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
